---
title: "Fiddlers"
author: "Jake Eisaguirre"
date: "8/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(kableExtra)
```


```{r}

fids <- read_csv(here("data", "HTL-MAR-FiddlerCrabBodySize.csv"))

```


## Data Exploration
Here we have a nice figure in which we can do some initial data exploration regarding carapace width by lattitude. 
```{r echo= FALSE}
ggplot(fids, aes(x = Latitude, y = carapace_width)) + 
  geom_point(aes(color = Latitude)) +
  labs(title = "Carapace Width by Latitude",
       x = "Latitude", 
       y = "Carapace Width (mm)", 
       caption = "Figure A is the observed Caprapace widths at latitude degrees") +
  theme_classic()
  
```









## Data Table
Here is a data table with some basic info about our fiddler crabs at different sites
```{r echo=F}

data <- fids %>%
  
  clean_names() %>% 
  
  group_by(site) %>% 
  
  summarize(mean_carapace_width = round(mean(carapace_width), 2), sd_carapace_width = round(sd(carapace_width), 2), sample_size = n())
  

kable(data, col.name = c("Site", "Mean Carapace Width (mm)", "SD Carapace Width (mm)", "Sample Size")) %>% 
  kable_classic()
  

```


## Temperate vs Carapace Width
Here we can see the possilbe correlation between mean carapce width and temperature
```{r, echo = FALSE, fig.alt = "Scatterplot of mean annual temperature compared to mean carapace width. Increases in temeperature result in decreases in mean width size."}
mean_data = fids %>% 
  clean_names() %>%
  group_by(matw) %>% 
  summarize(mean_carapace_width = mean(carapace_width))
  
ggplot(mean_data, aes(x = matw, y = mean_carapace_width)) + 
  geom_point() + 
  labs(title = "Mean Carapace Width by Temp", 
       x = "Mean Annual Water Temperature", 
       y = "Mean Carapace Width", 
       caption = "Figure B shows a negative trend in mean carapace width with increase in water temperature.") +
  theme_classic()

```

